/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.br.com.biblioteca.telas;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.util.Date;
import java.util.Optional;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UnsupportedLookAndFeelException;
import main.java.br.com.biblioteca.entidades.ClienteEntidade;
import main.java.br.com.biblioteca.entidades.RevistaEntidade;
import main.java.br.com.biblioteca.repositorios.ClienteRepositorio;
import main.java.br.com.biblioteca.repositorios.RevistaRepositorio;
import main.java.br.com.biblioteca.repositorios.interfaces.ClienteRepositorioInterface;
import main.java.br.com.biblioteca.repositorios.interfaces.RevistaRepositorioInterface;
import main.java.br.com.biblioteca.telas.geral.TabelaGeral;
import main.java.br.com.biblioteca.telas.geral.TelasGeral;
import main.java.br.com.biblioteca.telas.geral.ValidarGeral;
import main.java.br.com.biblioteca.utilitarios.conversores.ConversorTipos;

/**
 *
 * @author lucas
 */
public class Principal extends javax.swing.JFrame {

    public static final Integer LARGURA_IMAGEM = 150;
    public static final Integer ALTURA_IMAGEM = 150;

    private final ClienteRepositorioInterface CLIENTE_REPOSITORIO_INTERFACE = new ClienteRepositorio();
    private final RevistaRepositorioInterface REVISTA_REPOSITORIO_INTERFACE = new RevistaRepositorio();

    private static final Logger LOGGER = Logger.getLogger(Principal.class.getName());

    private File arquivoAtual = null;

    /**
     * Creates new form Teste
     */
    public Principal() {
        initComponents();
        atualizarTabelaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraLateralPanel = new javax.swing.JPanel();
        livroBarraLateralBtn = new javax.swing.JButton();
        clienteBarraLateralBtn = new javax.swing.JButton();
        compraBarraLateralBtn = new javax.swing.JButton();
        revistaBarraLateralBtn = new javax.swing.JButton();
        periodicoBarraLateralBtn = new javax.swing.JButton();
        paiPanel = new javax.swing.JPanel();
        clientePanel = new javax.swing.JPanel();
        cadastroClientePanel = new javax.swing.JPanel();
        atualizarClienteBtn = new javax.swing.JButton();
        cadastrarClienteBtn = new javax.swing.JButton();
        nomeClienteTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fotoClienteLbl = new javax.swing.JLabel();
        selecionarFotoClienteBtn = new javax.swing.JButton();
        cpfClienteTxt = new javax.swing.JFormattedTextField();
        dataNascimentoClienteTxt = new javax.swing.JFormattedTextField();
        telefoneClienteTxt = new javax.swing.JFormattedTextField();
        inativarClienteBtn = new javax.swing.JButton();
        statusClienteLbl = new javax.swing.JLabel();
        mostrarClienteInativoRadio = new javax.swing.JRadioButton();
        ativoClienteComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        listagemClientePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienteListagemTbl = new javax.swing.JTable();
        compraPanel = new javax.swing.JPanel();
        revistaPanel = new javax.swing.JPanel();
        cadastroRevistaPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        nomeRevistaTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cadastrarRevistaBtn = new javax.swing.JButton();
        atualizarRevistaBtn = new javax.swing.JButton();
        valorRevistaTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dataLancamentoRevistaTxt = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        editoraRevistaTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        fotoRevistaLbl = new javax.swing.JLabel();
        selecionarFotoRevistaBtn = new javax.swing.JButton();
        statusRevistaLbl = new javax.swing.JLabel();
        paginasRevistaSpinner = new javax.swing.JSpinner();
        edicaoRevistaSpinner = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        inativarRevistaBtn = new javax.swing.JButton();
        mostrarRevistaInativoRadio = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        ativoRevistaComboBox = new javax.swing.JComboBox<>();
        autorRevistaTxt = new javax.swing.JTextField();
        listagemRevistaPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        revistaListagemTbl = new javax.swing.JTable();
        periodicoPanel = new javax.swing.JPanel();
        cadastroPeriodicoPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        nomePeriodicoTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cadastrarPeriodicoBtn = new javax.swing.JButton();
        atualizarPeriodicoBtn = new javax.swing.JButton();
        valorPeriodicoTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        dataLancamentoPeriodicoTxt = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        editoraPeriodicoTxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fotoPeriodicoLbl = new javax.swing.JLabel();
        selecionarFotoPeriodicoBtn = new javax.swing.JButton();
        statusPeriodicoLbl = new javax.swing.JLabel();
        paginasPeriodicoSpinner = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        inativarPeriodicoBtn = new javax.swing.JButton();
        mostrarPeriodicoInativoRadio = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        ativoPeriodicoComboBox = new javax.swing.JComboBox<>();
        autorPeriodicoTxt = new javax.swing.JTextField();
        regiaoPeriodiTxt = new javax.swing.JTextField();
        listagemRevistaPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        periodicoListagemTbl = new javax.swing.JTable();
        livroPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barraLateralPanel.setBackground(new java.awt.Color(240, 150, 123));

        livroBarraLateralBtn.setText("Livro");
        livroBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livroBarraLateralBtnActionPerformed(evt);
            }
        });

        clienteBarraLateralBtn.setText("Cliente");
        clienteBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteBarraLateralBtnActionPerformed(evt);
            }
        });

        compraBarraLateralBtn.setText("Compra");
        compraBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraBarraLateralBtnActionPerformed(evt);
            }
        });

        revistaBarraLateralBtn.setText("Revista");
        revistaBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revistaBarraLateralBtnActionPerformed(evt);
            }
        });

        periodicoBarraLateralBtn.setText("Periódico");
        periodicoBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodicoBarraLateralBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraLateralPanelLayout = new javax.swing.GroupLayout(barraLateralPanel);
        barraLateralPanel.setLayout(barraLateralPanelLayout);
        barraLateralPanelLayout.setHorizontalGroup(
            barraLateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraLateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revistaBarraLateralBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(livroBarraLateralBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clienteBarraLateralBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compraBarraLateralBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(periodicoBarraLateralBtn)))
                .addContainerGap())
        );
        barraLateralPanelLayout.setVerticalGroup(
            barraLateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clienteBarraLateralBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compraBarraLateralBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(revistaBarraLateralBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(periodicoBarraLateralBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(livroBarraLateralBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paiPanel.setPreferredSize(new java.awt.Dimension(1125, 0));
        paiPanel.setLayout(new java.awt.CardLayout());

        clientePanel.setPreferredSize(new java.awt.Dimension(1135, 710));

        cadastroClientePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Cadastro"));
        cadastroClientePanel.setPreferredSize(new java.awt.Dimension(1115, 320));

        atualizarClienteBtn.setText("Atualizar");
        atualizarClienteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        atualizarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarClienteBtnActionPerformed(evt);
            }
        });

        cadastrarClienteBtn.setText("Cadastrar");
        cadastrarClienteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cadastrarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteBtnActionPerformed(evt);
            }
        });

        nomeClienteTxt.setBackground(new java.awt.Color(240, 240, 240));
        nomeClienteTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nomeClienteTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setText("Nome Completo");

        jLabel3.setText("CPF");

        jLabel4.setText("Data de Nascimento");

        jLabel5.setText("Telefone");

        fotoClienteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoClienteLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        selecionarFotoClienteBtn.setText("Selecionar");
        selecionarFotoClienteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        selecionarFotoClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarFotoClienteBtnActionPerformed(evt);
            }
        });

        cpfClienteTxt.setBackground(new java.awt.Color(240, 240, 240));
        cpfClienteTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            cpfClienteTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfClienteTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        dataNascimentoClienteTxt.setBackground(new java.awt.Color(240, 240, 240));
        dataNascimentoClienteTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            dataNascimentoClienteTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoClienteTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        telefoneClienteTxt.setBackground(new java.awt.Color(240, 240, 240));
        telefoneClienteTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            telefoneClienteTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneClienteTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        telefoneClienteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneClienteTxtActionPerformed(evt);
            }
        });

        inativarClienteBtn.setText("Inativar");
        inativarClienteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        inativarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inativarClienteBtnActionPerformed(evt);
            }
        });

        mostrarClienteInativoRadio.setText("Mostrar Inativos");
        mostrarClienteInativoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarClienteInativoRadioActionPerformed(evt);
            }
        });

        ativoClienteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        jLabel6.setText("Ativo");

        javax.swing.GroupLayout cadastroClientePanelLayout = new javax.swing.GroupLayout(cadastroClientePanel);
        cadastroClientePanel.setLayout(cadastroClientePanelLayout);
        cadastroClientePanelLayout.setHorizontalGroup(
            cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroClientePanelLayout.createSequentialGroup()
                        .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(cpfClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataNascimentoClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                                .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(ativoClienteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                        .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fotoClienteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(selecionarFotoClienteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addComponent(telefoneClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusClienteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrarClienteInativoRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atualizarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inativarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        cadastroClientePanelLayout.setVerticalGroup(
            cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroClientePanelLayout.createSequentialGroup()
                .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addComponent(fotoClienteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarFotoClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ativoClienteComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(nomeClienteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataNascimentoClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroClientePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mostrarClienteInativoRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inativarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(atualizarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cadastrarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(statusClienteLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        listagemClientePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Listagem"));
        listagemClientePanel.setPreferredSize(new java.awt.Dimension(464, 350));

        clienteListagemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome Completo", "Data de Nascimento", "CPF", "Telefone", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clienteListagemTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteListagemTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(clienteListagemTbl);
        if (clienteListagemTbl.getColumnModel().getColumnCount() > 0) {
            clienteListagemTbl.getColumnModel().getColumn(0).setResizable(false);
            clienteListagemTbl.getColumnModel().getColumn(1).setResizable(false);
            clienteListagemTbl.getColumnModel().getColumn(2).setResizable(false);
            clienteListagemTbl.getColumnModel().getColumn(3).setResizable(false);
            clienteListagemTbl.getColumnModel().getColumn(4).setResizable(false);
            clienteListagemTbl.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout listagemClientePanelLayout = new javax.swing.GroupLayout(listagemClientePanel);
        listagemClientePanel.setLayout(listagemClientePanelLayout);
        listagemClientePanelLayout.setHorizontalGroup(
            listagemClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemClientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        listagemClientePanelLayout.setVerticalGroup(
            listagemClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listagemClientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout clientePanelLayout = new javax.swing.GroupLayout(clientePanel);
        clientePanel.setLayout(clientePanelLayout);
        clientePanelLayout.setHorizontalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroClientePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
                    .addComponent(listagemClientePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE))
                .addContainerGap())
        );
        clientePanelLayout.setVerticalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroClientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listagemClientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paiPanel.add(clientePanel, "clienteCartao");

        javax.swing.GroupLayout compraPanelLayout = new javax.swing.GroupLayout(compraPanel);
        compraPanel.setLayout(compraPanelLayout);
        compraPanelLayout.setHorizontalGroup(
            compraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1141, Short.MAX_VALUE)
        );
        compraPanelLayout.setVerticalGroup(
            compraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        paiPanel.add(compraPanel, "compraCartao");

        cadastroRevistaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Cadastro"));

        jLabel7.setText("Nome");

        nomeRevistaTxt.setBackground(new java.awt.Color(240, 240, 240));
        nomeRevistaTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nomeRevistaTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setText("Valor");

        cadastrarRevistaBtn.setText("Cadastrar");
        cadastrarRevistaBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cadastrarRevistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarRevistaBtnActionPerformed(evt);
            }
        });

        atualizarRevistaBtn.setText("Atualizar");
        atualizarRevistaBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        atualizarRevistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarRevistaBtnActionPerformed(evt);
            }
        });

        valorRevistaTxt.setBackground(new java.awt.Color(240, 240, 240));
        valorRevistaTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        valorRevistaTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setText("Data de Lançamento");

        dataLancamentoRevistaTxt.setBackground(new java.awt.Color(240, 240, 240));
        dataLancamentoRevistaTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            dataLancamentoRevistaTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataLancamentoRevistaTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel10.setText("Paginas");

        jLabel11.setText("Editora");

        editoraRevistaTxt.setBackground(new java.awt.Color(240, 240, 240));
        editoraRevistaTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        editoraRevistaTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel12.setText("Edição");

        fotoRevistaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoRevistaLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        selecionarFotoRevistaBtn.setText("Selecionar");
        selecionarFotoRevistaBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        selecionarFotoRevistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarFotoRevistaBtnActionPerformed(evt);
            }
        });

        paginasRevistaSpinner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        edicaoRevistaSpinner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel13.setText("Autores");

        inativarRevistaBtn.setText("Inativar");
        inativarRevistaBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        inativarRevistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inativarRevistaBtnActionPerformed(evt);
            }
        });

        mostrarRevistaInativoRadio.setText("Mostrar Inativos");
        mostrarRevistaInativoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarRevistaInativoRadioActionPerformed(evt);
            }
        });

        jLabel14.setText("Ativo");

        ativoRevistaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        autorRevistaTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout cadastroRevistaPanelLayout = new javax.swing.GroupLayout(cadastroRevistaPanel);
        cadastroRevistaPanel.setLayout(cadastroRevistaPanelLayout);
        cadastroRevistaPanelLayout.setHorizontalGroup(
            cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroRevistaPanelLayout.createSequentialGroup()
                        .addComponent(mostrarRevistaInativoRadio)
                        .addGap(18, 18, 18)
                        .addComponent(cadastrarRevistaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atualizarRevistaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inativarRevistaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                        .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorRevistaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                                        .addComponent(edicaoRevistaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(statusRevistaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                                        .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(nomeRevistaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editoraRevistaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))
                                    .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroRevistaPanelLayout.createSequentialGroup()
                                            .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dataLancamentoRevistaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9))
                                            .addGap(18, 18, 18)
                                            .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14)
                                                .addComponent(ativoRevistaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroRevistaPanelLayout.createSequentialGroup()
                                            .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                                                    .addComponent(paginasRevistaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroRevistaPanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addGap(181, 181, 181)))
                                            .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(autorRevistaTxt)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fotoRevistaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selecionarFotoRevistaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        cadastroRevistaPanelLayout.setVerticalGroup(
            cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                        .addComponent(fotoRevistaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarFotoRevistaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroRevistaPanelLayout.createSequentialGroup()
                        .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroRevistaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editoraRevistaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE))
                            .addGroup(cadastroRevistaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeRevistaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusRevistaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(valorRevistaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                        .addComponent(edicaoRevistaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataLancamentoRevistaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ativoRevistaComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paginasRevistaSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(autorRevistaTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cadastroRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarRevistaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarRevistaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inativarRevistaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarRevistaInativoRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        listagemRevistaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Listagem"));

        revistaListagemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Valor (R$)", "Data de Lançamento", "Paginas", "Editora", "Edição", "Autor", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        revistaListagemTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                revistaListagemTblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(revistaListagemTbl);
        if (revistaListagemTbl.getColumnModel().getColumnCount() > 0) {
            revistaListagemTbl.getColumnModel().getColumn(0).setResizable(false);
            revistaListagemTbl.getColumnModel().getColumn(1).setResizable(false);
            revistaListagemTbl.getColumnModel().getColumn(2).setResizable(false);
            revistaListagemTbl.getColumnModel().getColumn(3).setResizable(false);
            revistaListagemTbl.getColumnModel().getColumn(4).setResizable(false);
            revistaListagemTbl.getColumnModel().getColumn(5).setResizable(false);
            revistaListagemTbl.getColumnModel().getColumn(6).setResizable(false);
            revistaListagemTbl.getColumnModel().getColumn(7).setResizable(false);
            revistaListagemTbl.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout listagemRevistaPanelLayout = new javax.swing.GroupLayout(listagemRevistaPanel);
        listagemRevistaPanel.setLayout(listagemRevistaPanelLayout);
        listagemRevistaPanelLayout.setHorizontalGroup(
            listagemRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemRevistaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        listagemRevistaPanelLayout.setVerticalGroup(
            listagemRevistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemRevistaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout revistaPanelLayout = new javax.swing.GroupLayout(revistaPanel);
        revistaPanel.setLayout(revistaPanelLayout);
        revistaPanelLayout.setHorizontalGroup(
            revistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revistaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(revistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listagemRevistaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroRevistaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        revistaPanelLayout.setVerticalGroup(
            revistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(revistaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroRevistaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listagemRevistaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        paiPanel.add(revistaPanel, "revistaCartao");

        cadastroPeriodicoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Cadastro"));

        jLabel15.setText("Nome");

        nomePeriodicoTxt.setBackground(new java.awt.Color(240, 240, 240));
        nomePeriodicoTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nomePeriodicoTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel16.setText("Valor");

        cadastrarPeriodicoBtn.setText("Cadastrar");
        cadastrarPeriodicoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cadastrarPeriodicoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarPeriodicoBtnActionPerformed(evt);
            }
        });

        atualizarPeriodicoBtn.setText("Atualizar");
        atualizarPeriodicoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        atualizarPeriodicoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarPeriodicoBtnActionPerformed(evt);
            }
        });

        valorPeriodicoTxt.setBackground(new java.awt.Color(240, 240, 240));
        valorPeriodicoTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        valorPeriodicoTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel17.setText("Data de Lançamento");

        dataLancamentoPeriodicoTxt.setBackground(new java.awt.Color(240, 240, 240));
        dataLancamentoPeriodicoTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            dataLancamentoPeriodicoTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataLancamentoPeriodicoTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel18.setText("Paginas");

        jLabel19.setText("Editora");

        editoraPeriodicoTxt.setBackground(new java.awt.Color(240, 240, 240));
        editoraPeriodicoTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        editoraPeriodicoTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel20.setText("Região");

        fotoPeriodicoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoPeriodicoLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        selecionarFotoPeriodicoBtn.setText("Selecionar");
        selecionarFotoPeriodicoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        selecionarFotoPeriodicoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarFotoPeriodicoBtnActionPerformed(evt);
            }
        });

        paginasPeriodicoSpinner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel21.setText("Autores");

        inativarPeriodicoBtn.setText("Inativar");
        inativarPeriodicoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        inativarPeriodicoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inativarPeriodicoBtnActionPerformed(evt);
            }
        });

        mostrarPeriodicoInativoRadio.setText("Mostrar Inativos");
        mostrarPeriodicoInativoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPeriodicoInativoRadioActionPerformed(evt);
            }
        });

        jLabel22.setText("Ativo");

        ativoPeriodicoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        autorPeriodicoTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        regiaoPeriodiTxt.setBackground(new java.awt.Color(240, 240, 240));
        regiaoPeriodiTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        regiaoPeriodiTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout cadastroPeriodicoPanelLayout = new javax.swing.GroupLayout(cadastroPeriodicoPanel);
        cadastroPeriodicoPanel.setLayout(cadastroPeriodicoPanelLayout);
        cadastroPeriodicoPanelLayout.setHorizontalGroup(
            cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPeriodicoPanelLayout.createSequentialGroup()
                        .addComponent(mostrarPeriodicoInativoRadio)
                        .addGap(18, 18, 18)
                        .addComponent(cadastrarPeriodicoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atualizarPeriodicoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inativarPeriodicoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                        .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                                .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorPeriodicoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                                        .addComponent(regiaoPeriodiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(statusPeriodicoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                                .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                                        .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(nomePeriodicoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editoraPeriodicoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19)))
                                    .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPeriodicoPanelLayout.createSequentialGroup()
                                            .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dataLancamentoPeriodicoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel17))
                                            .addGap(18, 18, 18)
                                            .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel22)
                                                .addComponent(ativoPeriodicoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPeriodicoPanelLayout.createSequentialGroup()
                                            .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                                                    .addComponent(paginasPeriodicoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPeriodicoPanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addGap(181, 181, 181)))
                                            .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel21)
                                                .addComponent(autorPeriodicoTxt)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fotoPeriodicoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selecionarFotoPeriodicoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        cadastroPeriodicoPanelLayout.setVerticalGroup(
            cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                        .addComponent(fotoPeriodicoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarFotoPeriodicoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPeriodicoPanelLayout.createSequentialGroup()
                        .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomePeriodicoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel20)))
                            .addGroup(cadastroPeriodicoPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editoraPeriodicoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addGap(39, 39, 39)))
                        .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusPeriodicoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorPeriodicoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regiaoPeriodiTxt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataLancamentoPeriodicoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ativoPeriodicoComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paginasPeriodicoSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(autorPeriodicoTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cadastroPeriodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarPeriodicoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarPeriodicoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inativarPeriodicoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarPeriodicoInativoRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        listagemRevistaPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Listagem"));

        periodicoListagemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Valor (R$)", "Data de Lançamento", "Paginas", "Editora", "Regição", "Autor", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        periodicoListagemTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                periodicoListagemTblMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(periodicoListagemTbl);
        if (periodicoListagemTbl.getColumnModel().getColumnCount() > 0) {
            periodicoListagemTbl.getColumnModel().getColumn(0).setResizable(false);
            periodicoListagemTbl.getColumnModel().getColumn(1).setResizable(false);
            periodicoListagemTbl.getColumnModel().getColumn(2).setResizable(false);
            periodicoListagemTbl.getColumnModel().getColumn(3).setResizable(false);
            periodicoListagemTbl.getColumnModel().getColumn(4).setResizable(false);
            periodicoListagemTbl.getColumnModel().getColumn(5).setResizable(false);
            periodicoListagemTbl.getColumnModel().getColumn(6).setResizable(false);
            periodicoListagemTbl.getColumnModel().getColumn(7).setResizable(false);
            periodicoListagemTbl.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout listagemRevistaPanel1Layout = new javax.swing.GroupLayout(listagemRevistaPanel1);
        listagemRevistaPanel1.setLayout(listagemRevistaPanel1Layout);
        listagemRevistaPanel1Layout.setHorizontalGroup(
            listagemRevistaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemRevistaPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        listagemRevistaPanel1Layout.setVerticalGroup(
            listagemRevistaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemRevistaPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout periodicoPanelLayout = new javax.swing.GroupLayout(periodicoPanel);
        periodicoPanel.setLayout(periodicoPanelLayout);
        periodicoPanelLayout.setHorizontalGroup(
            periodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodicoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(periodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroPeriodicoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listagemRevistaPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        periodicoPanelLayout.setVerticalGroup(
            periodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodicoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroPeriodicoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listagemRevistaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paiPanel.add(periodicoPanel, "periodicoCartao");

        javax.swing.GroupLayout livroPanelLayout = new javax.swing.GroupLayout(livroPanel);
        livroPanel.setLayout(livroPanelLayout);
        livroPanelLayout.setHorizontalGroup(
            livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1141, Short.MAX_VALUE)
        );
        livroPanelLayout.setVerticalGroup(
            livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        paiPanel.add(livroPanel, "livroCartao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraLateralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(paiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraLateralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void livroBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livroBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "livroCartao");
    }//GEN-LAST:event_livroBarraLateralBtnActionPerformed

    private void clienteBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "clienteCartao");
        atualizarTabelaCliente();
    }//GEN-LAST:event_clienteBarraLateralBtnActionPerformed

    private void compraBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "compraCartao");
    }//GEN-LAST:event_compraBarraLateralBtnActionPerformed

    private void revistaBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revistaBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "revistaCartao");
        atualizarTabelaRevista();
    }//GEN-LAST:event_revistaBarraLateralBtnActionPerformed

    private void periodicoBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodicoBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "periodicoCartao");
    }//GEN-LAST:event_periodicoBarraLateralBtnActionPerformed

    private void cadastrarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteBtnActionPerformed
        Boolean valido = ValidarGeral.clienteValido(
            nomeClienteTxt,
            cpfClienteTxt,
            dataNascimentoClienteTxt,
            telefoneClienteTxt,
            fotoClienteLbl,
            statusClienteLbl
        );

        if (valido.equals(Boolean.TRUE)) {

            Optional<ClienteEntidade> clienteEntidadeOptional = CLIENTE_REPOSITORIO_INTERFACE.buscarPorCpf(
                cpfClienteTxt.getText()
            );

            if (!clienteEntidadeOptional.isPresent()) {
                String nome = nomeClienteTxt.getText();
                String cpf = cpfClienteTxt.getText();
                Date dataNascimento = ConversorTipos.stringParaDate(dataNascimentoClienteTxt.getText());
                String telefone = telefoneClienteTxt.getText();
                Boolean ativo = ativoClienteComboBox.getSelectedIndex() == 0;

                ClienteEntidade clienteEntidade = new ClienteEntidade(
                    nome,
                    dataNascimento,
                    cpf,
                    telefone,
                    ativo,
                    ConversorTipos.fileParaByteArray(arquivoAtual)
                );

                CLIENTE_REPOSITORIO_INTERFACE.criar(clienteEntidade);

                atualizarTabelaCliente();
                limparCamposCliente();
            } else {
                statusClienteLbl.setForeground(Color.RED);
                statusClienteLbl.setText("Já existe um cliente com esse CPF.");
            }
        }
    }//GEN-LAST:event_cadastrarClienteBtnActionPerformed

    private void telefoneClienteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneClienteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneClienteTxtActionPerformed

    private void selecionarFotoClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarFotoClienteBtnActionPerformed
        JFileChooser jFileChooser = TelasGeral.seletorDeImagem();

        Integer abriu = jFileChooser.showOpenDialog(this);

        if (abriu.equals(JFileChooser.APPROVE_OPTION)) {
            File file = jFileChooser.getSelectedFile();
            arquivoAtual = file;
            ImageIcon imageIcon = TelasGeral.redimensionarImagem(
                file,
                LARGURA_IMAGEM,
                LARGURA_IMAGEM
            );

            fotoClienteLbl.setIcon(imageIcon);
        }
    }//GEN-LAST:event_selecionarFotoClienteBtnActionPerformed

    private void inativarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inativarClienteBtnActionPerformed
        if (TabelaGeral.linhaValida(clienteListagemTbl)) {
            ClienteEntidade clienteEntidade = TabelaGeral.convertParaClienteEntidade(
                clienteListagemTbl
            );
            clienteEntidade.setAtivo(Boolean.FALSE);
            CLIENTE_REPOSITORIO_INTERFACE.inativar(clienteEntidade.getId());

            atualizarTabelaCliente();
            limparCamposCliente();
        } else {
            statusClienteLbl.setForeground(Color.RED);
            statusClienteLbl.setText("Selecione uma linha");
        }

    }//GEN-LAST:event_inativarClienteBtnActionPerformed

    private void mostrarClienteInativoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarClienteInativoRadioActionPerformed
        atualizarTabelaCliente();
    }//GEN-LAST:event_mostrarClienteInativoRadioActionPerformed

    private void atualizarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarClienteBtnActionPerformed
        if (TabelaGeral.linhaValida(clienteListagemTbl)) {
            Boolean clienteValido = ValidarGeral.clienteValido(
                nomeClienteTxt,
                cpfClienteTxt,
                dataNascimentoClienteTxt,
                telefoneClienteTxt,
                fotoClienteLbl,
                statusClienteLbl
            );

            if (clienteValido) {
                String nome = nomeClienteTxt.getText();
                String cpf = cpfClienteTxt.getText();
                Date dataNascimento = ConversorTipos.stringParaDate(dataNascimentoClienteTxt.getText());
                String telefone = telefoneClienteTxt.getText();
                Boolean ativo = ativoClienteComboBox.getSelectedIndex() == 0;
                byte[] foto = ConversorTipos.iconParaByteArray(
                    fotoClienteLbl.getIcon()
                );

                ClienteEntidade clienteEntidade = TabelaGeral.convertParaClienteEntidade(clienteListagemTbl);
                clienteEntidade.setNomeCompleto(nome);
                clienteEntidade.setCpf(cpf);
                clienteEntidade.setDataNascimento(dataNascimento);
                clienteEntidade.setTelefone(telefone);
                clienteEntidade.setAtivo(ativo);
                clienteEntidade.setFoto(foto);

                CLIENTE_REPOSITORIO_INTERFACE.atualizar(clienteEntidade);

                atualizarTabelaCliente();
                limparCamposCliente();
            }
        } else {
            statusClienteLbl.setForeground(Color.red);
            statusClienteLbl.setText("Um registro deve estar selecionado para autalizar.");
        }
    }//GEN-LAST:event_atualizarClienteBtnActionPerformed

    private void clienteListagemTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteListagemTblMouseClicked
        if (TabelaGeral.linhaValida(clienteListagemTbl)) {
            ClienteEntidade clienteEntidade = TabelaGeral.convertParaClienteEntidade(clienteListagemTbl);
            Optional<ClienteEntidade> optional = CLIENTE_REPOSITORIO_INTERFACE.buscarPorId(clienteEntidade.getId());

            if (optional.isPresent()) {
                clienteEntidade = optional.get();

                nomeClienteTxt.setText(clienteEntidade.getNomeCompleto());
                cpfClienteTxt.setText(clienteEntidade.getCpf());
                dataNascimentoClienteTxt.setText(
                    ConversorTipos.dateParaString(
                        clienteEntidade.getDataNascimento()
                    )
                );
                telefoneClienteTxt.setText(clienteEntidade.getTelefone());

                Integer ativoIndex = clienteEntidade.getAtivo().equals(Boolean.TRUE)
                    ? 0
                    : 1;
                ativoClienteComboBox.setSelectedIndex(ativoIndex);

                Icon icone = ConversorTipos.byteArrayParaIcon(clienteEntidade.getFoto());
                fotoClienteLbl.setIcon(icone);
            }
        }
    }//GEN-LAST:event_clienteListagemTblMouseClicked

    private void cadastrarRevistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarRevistaBtnActionPerformed
        Boolean revistaValida = ValidarGeral.revistaValida(
            nomeRevistaTxt,
            valorRevistaTxt,
            dataLancamentoRevistaTxt,
            paginasRevistaSpinner,
            editoraRevistaTxt,
            autorRevistaTxt,
            edicaoRevistaSpinner,
            fotoRevistaLbl,
            statusRevistaLbl
        );

        if (revistaValida) {
            String nome = nomeRevistaTxt.getText();
            Double valor = Double.valueOf(
                valorRevistaTxt.getText()
            );
            Date dataLancamento = ConversorTipos.stringParaDate(
                dataLancamentoRevistaTxt.getText()
            );
            Integer paginas = (Integer) paginasRevistaSpinner.getValue();
            String editora = editoraRevistaTxt.getText();
            String autor = autorRevistaTxt.getText();
            Integer edicao = (Integer) edicaoRevistaSpinner.getValue();
            byte[] foto = ConversorTipos.fileParaByteArray(arquivoAtual);
            Boolean ativo = ativoRevistaComboBox.getSelectedIndex() == 0;

            RevistaEntidade revista = new RevistaEntidade(
                nome,
                valor,
                dataLancamento,
                paginas,
                editora,
                autor,
                foto,
                edicao,
                ativo
            );

            REVISTA_REPOSITORIO_INTERFACE.criar(revista);

            atualizarTabelaRevista();
            limparCamposRevista();
        }
    }//GEN-LAST:event_cadastrarRevistaBtnActionPerformed

    private void atualizarRevistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarRevistaBtnActionPerformed
        if (TabelaGeral.linhaValida(revistaListagemTbl)) {
            Boolean revistaValida = ValidarGeral.revistaValida(
                nomeRevistaTxt,
                valorRevistaTxt,
                dataLancamentoRevistaTxt,
                paginasRevistaSpinner,
                editoraRevistaTxt,
                autorRevistaTxt,
                edicaoRevistaSpinner,
                fotoRevistaLbl,
                statusRevistaLbl
            );

            if (revistaValida) {
                String nome = nomeRevistaTxt.getText();
                Double valor = Double.valueOf(
                    valorRevistaTxt.getText()
                );
                Date dataLancamento = ConversorTipos.stringParaDate(
                    dataLancamentoRevistaTxt.getText()
                );
                Integer paginas = (Integer) paginasRevistaSpinner.getValue();
                String editora = editoraRevistaTxt.getText();
                String autor = autorRevistaTxt.getText();
                Integer edicao = (Integer) edicaoRevistaSpinner.getValue();
                byte[] foto = ConversorTipos.iconParaByteArray(
                    fotoRevistaLbl.getIcon()
                );
                Boolean ativo = ativoRevistaComboBox.getSelectedIndex() == 0;

                RevistaEntidade revista = TabelaGeral.convertParaRevistaEntidade(revistaListagemTbl);
                revista = REVISTA_REPOSITORIO_INTERFACE.buscarPorId(revista.getId()).get();
                revista.setNome(nome);
                revista.setValor(valor);
                revista.setDataLancamento(dataLancamento);
                revista.setPaginas(paginas);
                revista.setEditora(editora);
                revista.setAutor(autor);
                revista.setFoto(foto);
                revista.setEdicao(edicao);
                revista.setAtivo(ativo);

                REVISTA_REPOSITORIO_INTERFACE.atualizar(revista);

                atualizarTabelaRevista();
                limparCamposRevista();
            }
        } else {
            statusClienteLbl.setForeground(Color.red);
            statusClienteLbl.setText("Um registro deve estar selecionado para autalizar.");
        }
    }//GEN-LAST:event_atualizarRevistaBtnActionPerformed

    private void selecionarFotoRevistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarFotoRevistaBtnActionPerformed
        JFileChooser jFileChooser = TelasGeral.seletorDeImagem();

        Integer abriu = jFileChooser.showOpenDialog(this);

        if (abriu.equals(JFileChooser.APPROVE_OPTION)) {
            File file = jFileChooser.getSelectedFile();
            arquivoAtual = file;
            ImageIcon imageIcon = TelasGeral.redimensionarImagem(
                file,
                LARGURA_IMAGEM,
                LARGURA_IMAGEM
            );

            fotoRevistaLbl.setIcon(imageIcon);
        }
    }//GEN-LAST:event_selecionarFotoRevistaBtnActionPerformed

    private void inativarRevistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inativarRevistaBtnActionPerformed
        if (TabelaGeral.linhaValida(revistaListagemTbl)) {
            RevistaEntidade revista = TabelaGeral.convertParaRevistaEntidade(
                revistaListagemTbl
            );
            revista.setAtivo(Boolean.FALSE);
            REVISTA_REPOSITORIO_INTERFACE.inativar(revista.getId());

            atualizarTabelaRevista();
            limparCamposRevista();
        } else {
            statusClienteLbl.setForeground(Color.RED);
            statusClienteLbl.setText("Selecione uma linha");
        }
    }//GEN-LAST:event_inativarRevistaBtnActionPerformed

    private void mostrarRevistaInativoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarRevistaInativoRadioActionPerformed
        atualizarTabelaRevista();
    }//GEN-LAST:event_mostrarRevistaInativoRadioActionPerformed

    private void revistaListagemTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_revistaListagemTblMouseClicked
        if (TabelaGeral.linhaValida(revistaListagemTbl)) {
            RevistaEntidade revista = TabelaGeral.convertParaRevistaEntidade(revistaListagemTbl);
            Optional<RevistaEntidade> revistaOptional = REVISTA_REPOSITORIO_INTERFACE.buscarPorId(revista.getId());

            revista = revistaOptional.get();

            Integer ativoIndex = revista.getAtivo().equals(Boolean.TRUE)
                ? 0
                : 1;

            nomeRevistaTxt.setText(revista.getNome());
            valorRevistaTxt.setText(revista.getValor().toString());
            dataLancamentoRevistaTxt.setText(
                ConversorTipos.dateParaString(
                    revista.getDataLancamento()
                )
            );
            paginasRevistaSpinner.setValue(revista.getPaginas());
            editoraRevistaTxt.setText(revista.getEditora());
            edicaoRevistaSpinner.setValue(revista.getEdicao());
            ativoRevistaComboBox.setSelectedIndex(ativoIndex);
            autorRevistaTxt.setText(revista.getAutor());

            Icon icone = ConversorTipos.byteArrayParaIcon(revista.getFoto());
            fotoRevistaLbl.setIcon(icone);
        }
    }//GEN-LAST:event_revistaListagemTblMouseClicked

    private void cadastrarPeriodicoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPeriodicoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarPeriodicoBtnActionPerformed

    private void atualizarPeriodicoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarPeriodicoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarPeriodicoBtnActionPerformed

    private void selecionarFotoPeriodicoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarFotoPeriodicoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarFotoPeriodicoBtnActionPerformed

    private void inativarPeriodicoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inativarPeriodicoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inativarPeriodicoBtnActionPerformed

    private void mostrarPeriodicoInativoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPeriodicoInativoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarPeriodicoInativoRadioActionPerformed

    private void periodicoListagemTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_periodicoListagemTblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_periodicoListagemTblMouseClicked

    private void atualizarTabelaCliente() {
        if (mostrarClienteInativoRadio.isSelected()) {
            TabelaGeral.atualizarTabelaCliente(
                clienteListagemTbl,
                CLIENTE_REPOSITORIO_INTERFACE.buscar()
            );
        } else {
            TabelaGeral.atualizarTabelaCliente(
                clienteListagemTbl,
                CLIENTE_REPOSITORIO_INTERFACE.buscarAtivos()
            );
        }
    }

    private void atualizarTabelaRevista() {
        if (mostrarRevistaInativoRadio.isSelected()) {
            TabelaGeral.atualizarTabelaRevista(
                revistaListagemTbl,
                REVISTA_REPOSITORIO_INTERFACE.buscar()
            );
        } else {
            TabelaGeral.atualizarTabelaRevista(
                revistaListagemTbl,
                REVISTA_REPOSITORIO_INTERFACE.buscarAtivos()
            );
        }
    }

    private void limparCamposCliente() {
        nomeClienteTxt.setText(null);
        cpfClienteTxt.setText(null);
        dataNascimentoClienteTxt.setText(null);
        telefoneClienteTxt.setText(null);
        ativoClienteComboBox.setSelectedIndex(0);
        fotoClienteLbl.setIcon(null);
    }

    private void limparCamposRevista() {
        nomeRevistaTxt.setText(null);
        valorRevistaTxt.setText(null);
        dataLancamentoRevistaTxt.setText(null);
        paginasRevistaSpinner.setValue(0);
        editoraRevistaTxt.setText(null);
        edicaoRevistaSpinner.setValue(0);
        ativoRevistaComboBox.setSelectedIndex(0);
        autorRevistaTxt.setText(null);
        fotoRevistaLbl.setIcon(null);
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            LOGGER.log(
                java.util.logging.Level.SEVERE,
                null,
                ex
            );
        }

        java.awt.EventQueue.invokeLater(
            () -> {
                new Principal().setVisible(true);
            }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ativoClienteComboBox;
    private javax.swing.JComboBox<String> ativoPeriodicoComboBox;
    private javax.swing.JComboBox<String> ativoRevistaComboBox;
    private javax.swing.JButton atualizarClienteBtn;
    private javax.swing.JButton atualizarPeriodicoBtn;
    private javax.swing.JButton atualizarRevistaBtn;
    private javax.swing.JTextField autorPeriodicoTxt;
    private javax.swing.JTextField autorRevistaTxt;
    private javax.swing.JPanel barraLateralPanel;
    private javax.swing.JButton cadastrarClienteBtn;
    private javax.swing.JButton cadastrarPeriodicoBtn;
    private javax.swing.JButton cadastrarRevistaBtn;
    private javax.swing.JPanel cadastroClientePanel;
    private javax.swing.JPanel cadastroPeriodicoPanel;
    private javax.swing.JPanel cadastroRevistaPanel;
    private javax.swing.JButton clienteBarraLateralBtn;
    private javax.swing.JTable clienteListagemTbl;
    private javax.swing.JPanel clientePanel;
    private javax.swing.JButton compraBarraLateralBtn;
    private javax.swing.JPanel compraPanel;
    private javax.swing.JFormattedTextField cpfClienteTxt;
    private javax.swing.JFormattedTextField dataLancamentoPeriodicoTxt;
    private javax.swing.JFormattedTextField dataLancamentoRevistaTxt;
    private javax.swing.JFormattedTextField dataNascimentoClienteTxt;
    private javax.swing.JSpinner edicaoRevistaSpinner;
    private javax.swing.JTextField editoraPeriodicoTxt;
    private javax.swing.JTextField editoraRevistaTxt;
    private javax.swing.JLabel fotoClienteLbl;
    private javax.swing.JLabel fotoPeriodicoLbl;
    private javax.swing.JLabel fotoRevistaLbl;
    private javax.swing.JButton inativarClienteBtn;
    private javax.swing.JButton inativarPeriodicoBtn;
    private javax.swing.JButton inativarRevistaBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel listagemClientePanel;
    private javax.swing.JPanel listagemRevistaPanel;
    private javax.swing.JPanel listagemRevistaPanel1;
    private javax.swing.JButton livroBarraLateralBtn;
    private javax.swing.JPanel livroPanel;
    private javax.swing.JRadioButton mostrarClienteInativoRadio;
    private javax.swing.JRadioButton mostrarPeriodicoInativoRadio;
    private javax.swing.JRadioButton mostrarRevistaInativoRadio;
    private javax.swing.JTextField nomeClienteTxt;
    private javax.swing.JTextField nomePeriodicoTxt;
    private javax.swing.JTextField nomeRevistaTxt;
    private javax.swing.JSpinner paginasPeriodicoSpinner;
    private javax.swing.JSpinner paginasRevistaSpinner;
    private javax.swing.JPanel paiPanel;
    private javax.swing.JButton periodicoBarraLateralBtn;
    private javax.swing.JTable periodicoListagemTbl;
    private javax.swing.JPanel periodicoPanel;
    private javax.swing.JTextField regiaoPeriodiTxt;
    private javax.swing.JButton revistaBarraLateralBtn;
    private javax.swing.JTable revistaListagemTbl;
    private javax.swing.JPanel revistaPanel;
    private javax.swing.JButton selecionarFotoClienteBtn;
    private javax.swing.JButton selecionarFotoPeriodicoBtn;
    private javax.swing.JButton selecionarFotoRevistaBtn;
    private javax.swing.JLabel statusClienteLbl;
    private javax.swing.JLabel statusPeriodicoLbl;
    private javax.swing.JLabel statusRevistaLbl;
    private javax.swing.JFormattedTextField telefoneClienteTxt;
    private javax.swing.JTextField valorPeriodicoTxt;
    private javax.swing.JTextField valorRevistaTxt;
    // End of variables declaration//GEN-END:variables
}
