/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.br.com.biblioteca.telas;

import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import main.java.br.com.biblioteca.entidades.AutorEntidade;
import main.java.br.com.biblioteca.entidades.ClienteEntidade;
import main.java.br.com.biblioteca.repositorios.AutorRepositorio;
import main.java.br.com.biblioteca.repositorios.ClienteRepositorio;
import main.java.br.com.biblioteca.repositorios.interfaces.AutorRepositorioInterface;
import main.java.br.com.biblioteca.repositorios.interfaces.ClienteRepositorioInterface;
import main.java.br.com.biblioteca.telas.geral.TabelaGeral;
import main.java.br.com.biblioteca.telas.geral.TelasGeral;
import main.java.br.com.biblioteca.telas.geral.ValidarGeral;
import main.java.br.com.biblioteca.utilitarios.conversores.ConversorTipos;

/**
 *
 * @author lucas
 */
public class Principal extends javax.swing.JFrame {

    private static final Integer LARGURA_IMAGEM = 150;
    private static final Integer ALTURA_IMAGEM = 150;

    private AutorRepositorioInterface autorRepositorioInterface = new AutorRepositorio();
    private ClienteRepositorioInterface clienteRepositorioInterface = new ClienteRepositorio();

    private static final Logger LOGGER = Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Teste
     */
    public Principal() {
        initComponents();
        TabelaGeral.atualizarTabelaAutor(autorListagemTbl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraLateralPanel = new javax.swing.JPanel();
        livroBarraLateralBtn = new javax.swing.JButton();
        autorBarraLateralBtn = new javax.swing.JButton();
        clienteBarraLateralBtn = new javax.swing.JButton();
        compraBarraLateralBtn = new javax.swing.JButton();
        revistaBarraLateralBtn = new javax.swing.JButton();
        periodicoBarraLateralBtn = new javax.swing.JButton();
        paiPanel = new javax.swing.JPanel();
        autorPanel = new javax.swing.JPanel();
        cadastroAutorPanel = new javax.swing.JPanel();
        nomeAutorTxt = new javax.swing.JTextField();
        cadastrarAutorBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        statusAutorLbl = new javax.swing.JLabel();
        atualizarAutorBtn = new javax.swing.JButton();
        deletarAutorBtn = new javax.swing.JButton();
        listagemAutorPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        autorListagemTbl = new javax.swing.JTable();
        clientePanel = new javax.swing.JPanel();
        cadastroClientePanel = new javax.swing.JPanel();
        atualizarClienteBtn = new javax.swing.JButton();
        cadastrarClienteBtn = new javax.swing.JButton();
        nomeClienteTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fotoClienteLbl = new javax.swing.JLabel();
        selecionarFotoClienteBtn = new javax.swing.JButton();
        cpfClienteTxt = new javax.swing.JFormattedTextField();
        dataNascimentoClienteTxt = new javax.swing.JFormattedTextField();
        telefoneClienteTxt = new javax.swing.JFormattedTextField();
        deletarClienteBtn = new javax.swing.JButton();
        statusClienteLbl = new javax.swing.JLabel();
        listagemClientePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clienteListagemTbl = new javax.swing.JTable();
        compraPanel = new javax.swing.JPanel();
        revistaPanel = new javax.swing.JPanel();
        periodicoPanel = new javax.swing.JPanel();
        livroPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barraLateralPanel.setBackground(new java.awt.Color(240, 150, 123));

        livroBarraLateralBtn.setText("Livro");
        livroBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livroBarraLateralBtnActionPerformed(evt);
            }
        });

        autorBarraLateralBtn.setText("Autor");
        autorBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorBarraLateralBtnActionPerformed(evt);
            }
        });

        clienteBarraLateralBtn.setText("Cliente");
        clienteBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteBarraLateralBtnActionPerformed(evt);
            }
        });

        compraBarraLateralBtn.setText("Compra");
        compraBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraBarraLateralBtnActionPerformed(evt);
            }
        });

        revistaBarraLateralBtn.setText("Revista");
        revistaBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revistaBarraLateralBtnActionPerformed(evt);
            }
        });

        periodicoBarraLateralBtn.setText("Periódico");
        periodicoBarraLateralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodicoBarraLateralBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraLateralPanelLayout = new javax.swing.GroupLayout(barraLateralPanel);
        barraLateralPanel.setLayout(barraLateralPanelLayout);
        barraLateralPanelLayout.setHorizontalGroup(
            barraLateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraLateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revistaBarraLateralBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(livroBarraLateralBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autorBarraLateralBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clienteBarraLateralBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compraBarraLateralBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLateralPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(periodicoBarraLateralBtn)))
                .addContainerGap())
        );
        barraLateralPanelLayout.setVerticalGroup(
            barraLateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLateralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autorBarraLateralBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clienteBarraLateralBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compraBarraLateralBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(revistaBarraLateralBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(periodicoBarraLateralBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(livroBarraLateralBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paiPanel.setPreferredSize(new java.awt.Dimension(1125, 0));
        paiPanel.setLayout(new java.awt.CardLayout());

        cadastroAutorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Cadastro"));

        nomeAutorTxt.setBackground(new java.awt.Color(240, 240, 240));
        nomeAutorTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nomeAutorTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cadastrarAutorBtn.setText("Cadastrar");
        cadastrarAutorBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cadastrarAutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarAutorBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        statusAutorLbl.setBackground(new java.awt.Color(255, 255, 255));

        atualizarAutorBtn.setText("Atualizar");
        atualizarAutorBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        atualizarAutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarAutorBtnActionPerformed(evt);
            }
        });

        deletarAutorBtn.setText("Deletar");
        deletarAutorBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        deletarAutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarAutorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cadastroAutorPanelLayout = new javax.swing.GroupLayout(cadastroAutorPanel);
        cadastroAutorPanel.setLayout(cadastroAutorPanelLayout);
        cadastroAutorPanelLayout.setHorizontalGroup(
            cadastroAutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroAutorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroAutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroAutorPanelLayout.createSequentialGroup()
                        .addComponent(statusAutorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarAutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atualizarAutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletarAutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastroAutorPanelLayout.createSequentialGroup()
                        .addGroup(cadastroAutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeAutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cadastroAutorPanelLayout.setVerticalGroup(
            cadastroAutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroAutorPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeAutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(cadastroAutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroAutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(atualizarAutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastrarAutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deletarAutorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statusAutorLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        listagemAutorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Listagem"));

        autorListagemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        autorListagemTbl.getTableHeader().setReorderingAllowed(false);
        autorListagemTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autorListagemTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(autorListagemTbl);
        if (autorListagemTbl.getColumnModel().getColumnCount() > 0) {
            autorListagemTbl.getColumnModel().getColumn(0).setResizable(false);
            autorListagemTbl.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout listagemAutorPanelLayout = new javax.swing.GroupLayout(listagemAutorPanel);
        listagemAutorPanel.setLayout(listagemAutorPanelLayout);
        listagemAutorPanelLayout.setHorizontalGroup(
            listagemAutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemAutorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
                .addContainerGap())
        );
        listagemAutorPanelLayout.setVerticalGroup(
            listagemAutorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemAutorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout autorPanelLayout = new javax.swing.GroupLayout(autorPanel);
        autorPanel.setLayout(autorPanelLayout);
        autorPanelLayout.setHorizontalGroup(
            autorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(autorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroAutorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listagemAutorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        autorPanelLayout.setVerticalGroup(
            autorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(autorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroAutorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listagemAutorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        paiPanel.add(autorPanel, "autorCartao");

        clientePanel.setPreferredSize(new java.awt.Dimension(1135, 710));

        cadastroClientePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Cadastro"));
        cadastroClientePanel.setPreferredSize(new java.awt.Dimension(1115, 320));

        atualizarClienteBtn.setText("Atualizar");
        atualizarClienteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cadastrarClienteBtn.setText("Cadastrar");
        cadastrarClienteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cadastrarClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteBtnActionPerformed(evt);
            }
        });

        nomeClienteTxt.setBackground(new java.awt.Color(240, 240, 240));
        nomeClienteTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        nomeClienteTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setText("Nome Completo");

        jLabel3.setText("CPF");

        jLabel4.setText("Data de Nascimento");

        jLabel5.setText("Telefone");

        fotoClienteLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoClienteLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        selecionarFotoClienteBtn.setText("Selecionar");
        selecionarFotoClienteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        selecionarFotoClienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarFotoClienteBtnActionPerformed(evt);
            }
        });

        cpfClienteTxt.setBackground(new java.awt.Color(240, 240, 240));
        cpfClienteTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            cpfClienteTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfClienteTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        dataNascimentoClienteTxt.setBackground(new java.awt.Color(240, 240, 240));
        dataNascimentoClienteTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            dataNascimentoClienteTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoClienteTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        telefoneClienteTxt.setBackground(new java.awt.Color(240, 240, 240));
        telefoneClienteTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        try {
            telefoneClienteTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneClienteTxt.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        telefoneClienteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneClienteTxtActionPerformed(evt);
            }
        });

        deletarClienteBtn.setText("Deletar");
        deletarClienteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout cadastroClientePanelLayout = new javax.swing.GroupLayout(cadastroClientePanel);
        cadastroClientePanel.setLayout(cadastroClientePanelLayout);
        cadastroClientePanelLayout.setHorizontalGroup(
            cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroClientePanelLayout.createSequentialGroup()
                        .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                                .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(cpfClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                                .addComponent(dataNascimentoClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fotoClienteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(selecionarFotoClienteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addComponent(telefoneClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusClienteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(atualizarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        cadastroClientePanelLayout.setVerticalGroup(
            cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroClientePanelLayout.createSequentialGroup()
                .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addComponent(fotoClienteLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarFotoClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cpfClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataNascimentoClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroClientePanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneClienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroClientePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cadastroClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deletarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(atualizarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cadastrarClienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(statusClienteLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        listagemClientePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Listagem"));
        listagemClientePanel.setPreferredSize(new java.awt.Dimension(464, 350));

        clienteListagemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome Completo", "Data de Nascimento", "CPF", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clienteListagemTbl.setPreferredSize(new java.awt.Dimension(150, 0));
        jScrollPane2.setViewportView(clienteListagemTbl);

        javax.swing.GroupLayout listagemClientePanelLayout = new javax.swing.GroupLayout(listagemClientePanel);
        listagemClientePanel.setLayout(listagemClientePanelLayout);
        listagemClientePanelLayout.setHorizontalGroup(
            listagemClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemClientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
                .addContainerGap())
        );
        listagemClientePanelLayout.setVerticalGroup(
            listagemClientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listagemClientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout clientePanelLayout = new javax.swing.GroupLayout(clientePanel);
        clientePanel.setLayout(clientePanelLayout);
        clientePanelLayout.setHorizontalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroClientePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listagemClientePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE))
                .addContainerGap())
        );
        clientePanelLayout.setVerticalGroup(
            clientePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroClientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listagemClientePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paiPanel.add(clientePanel, "clienteCartao");

        javax.swing.GroupLayout compraPanelLayout = new javax.swing.GroupLayout(compraPanel);
        compraPanel.setLayout(compraPanelLayout);
        compraPanelLayout.setHorizontalGroup(
            compraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1135, Short.MAX_VALUE)
        );
        compraPanelLayout.setVerticalGroup(
            compraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        paiPanel.add(compraPanel, "compraCartao");

        javax.swing.GroupLayout revistaPanelLayout = new javax.swing.GroupLayout(revistaPanel);
        revistaPanel.setLayout(revistaPanelLayout);
        revistaPanelLayout.setHorizontalGroup(
            revistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1135, Short.MAX_VALUE)
        );
        revistaPanelLayout.setVerticalGroup(
            revistaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        paiPanel.add(revistaPanel, "revistaCartao");

        javax.swing.GroupLayout periodicoPanelLayout = new javax.swing.GroupLayout(periodicoPanel);
        periodicoPanel.setLayout(periodicoPanelLayout);
        periodicoPanelLayout.setHorizontalGroup(
            periodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1135, Short.MAX_VALUE)
        );
        periodicoPanelLayout.setVerticalGroup(
            periodicoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        paiPanel.add(periodicoPanel, "periodicoCartao");

        javax.swing.GroupLayout livroPanelLayout = new javax.swing.GroupLayout(livroPanel);
        livroPanel.setLayout(livroPanelLayout);
        livroPanelLayout.setHorizontalGroup(
            livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1135, Short.MAX_VALUE)
        );
        livroPanelLayout.setVerticalGroup(
            livroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        paiPanel.add(livroPanel, "livroCartao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraLateralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraLateralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void livroBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livroBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "livroCartao");
    }//GEN-LAST:event_livroBarraLateralBtnActionPerformed

    private void autorBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "autorCartao");
        TabelaGeral.atualizarTabelaAutor(autorListagemTbl);
    }//GEN-LAST:event_autorBarraLateralBtnActionPerformed

    private void clienteBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "clienteCartao");
    }//GEN-LAST:event_clienteBarraLateralBtnActionPerformed

    private void compraBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "compraCartao");
    }//GEN-LAST:event_compraBarraLateralBtnActionPerformed

    private void revistaBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revistaBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "revistaCartao");
    }//GEN-LAST:event_revistaBarraLateralBtnActionPerformed

    private void periodicoBarraLateralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodicoBarraLateralBtnActionPerformed
        CardLayout principalCardLayout = (CardLayout) paiPanel.getLayout();
        principalCardLayout.show(paiPanel, "periodicoCartao");
    }//GEN-LAST:event_periodicoBarraLateralBtnActionPerformed

    private void cadastrarAutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarAutorBtnActionPerformed
        if (ValidarGeral.autorValido(nomeAutorTxt, statusAutorLbl)) {
            AutorEntidade autorEntidade = new AutorEntidade(
                    nomeAutorTxt.getText(),
                    null
            );

            autorRepositorioInterface.criar(autorEntidade);
            TabelaGeral.atualizarTabelaAutor(autorListagemTbl);
        }
    }//GEN-LAST:event_cadastrarAutorBtnActionPerformed

    private void cadastrarClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteBtnActionPerformed
        Boolean valido = ValidarGeral.clienteValido(
                nomeClienteTxt,
                cpfClienteTxt,
                dataNascimentoClienteTxt,
                telefoneClienteTxt,
                fotoClienteLbl,
                statusClienteLbl
        );

        if (valido.equals(Boolean.TRUE)) {
            String nome = nomeClienteTxt.getText();
            String cpf = cpfClienteTxt.getText();
            Date dataNascimento = ConversorTipos.stringParaDate(dataNascimentoClienteTxt.getText());
            String telefone = telefoneClienteTxt.getText();
            ImageIcon foto = new ImageIcon();
            
            
            ClienteEntidade clienteEntidade = new ClienteEntidade(
                    nome,
                    dataNascimento,
                    cpf,
                    telefone,
                    new byte[10],
                    new ArrayList<>()
            );

            clienteRepositorioInterface.criar(clienteEntidade);
        }
    }//GEN-LAST:event_cadastrarClienteBtnActionPerformed

    private void telefoneClienteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneClienteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneClienteTxtActionPerformed

    private void selecionarFotoClienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarFotoClienteBtnActionPerformed
        JFileChooser jFileChooser = TelasGeral.seletorDeImagem();

        Integer abriu = jFileChooser.showOpenDialog(this);

        if (abriu.equals(JFileChooser.APPROVE_OPTION)) {
            File file = jFileChooser.getSelectedFile();
            Icon icon = TelasGeral.redimensionarImagem(file, LARGURA_IMAGEM, LARGURA_IMAGEM);

            fotoClienteLbl.setIcon(icon);
        }
    }//GEN-LAST:event_selecionarFotoClienteBtnActionPerformed

    private void deletarAutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarAutorBtnActionPerformed
        if (TabelaGeral.linhaValida(autorListagemTbl)) {
            AutorEntidade autorEntidade = TabelaGeral.convertParaAutorEntidade(autorListagemTbl);
            Boolean acervoCinculado = autorRepositorioInterface.acervoVinculado(autorEntidade);

            if (!acervoCinculado) {
                autorRepositorioInterface.deletarPorId(autorEntidade.getId());
                DefaultTableModel defaultTableModel = (DefaultTableModel) autorListagemTbl.getModel();
                defaultTableModel.removeRow(TabelaGeral.pegarLinhaSelecionada(autorListagemTbl));

                statusAutorLbl.setForeground(Color.BLACK);
                statusAutorLbl.setText("Autor excluido com sucesso");
            } else {
                statusAutorLbl.setText(
                        "Não foi possível excluir, pois existem Livros, "
                        + "Revista ou Periódicos vinculados a esse autor!"
                );
            }
        }
    }//GEN-LAST:event_deletarAutorBtnActionPerformed

    private void autorListagemTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autorListagemTblMouseClicked
        if (TabelaGeral.linhaValida(autorListagemTbl)) {
            AutorEntidade autorEntidade = TabelaGeral.convertParaAutorEntidade(autorListagemTbl);
            nomeAutorTxt.setText(autorEntidade.getNome());
        }
    }//GEN-LAST:event_autorListagemTblMouseClicked

    private void atualizarAutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarAutorBtnActionPerformed
        if (TabelaGeral.linhaValida(autorListagemTbl)) {
            if (ValidarGeral.autorValido(nomeAutorTxt, statusAutorLbl)) {
                AutorEntidade autorEntidade = TabelaGeral.convertParaAutorEntidade(autorListagemTbl);
                autorEntidade.setNome(nomeAutorTxt.getText());
                autorRepositorioInterface.atualizar(autorEntidade);

                TabelaGeral.atualizarTabelaAutor(autorListagemTbl);
            }
        } else {
            statusAutorLbl.setForeground(Color.red);
            statusAutorLbl.setText("Um registro deve estar selecionado para autalizar.");
        }
    }//GEN-LAST:event_atualizarAutorBtnActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            LOGGER.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

        java.awt.EventQueue.invokeLater(
                () -> {
                    new Principal().setVisible(true);
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarAutorBtn;
    private javax.swing.JButton atualizarClienteBtn;
    private javax.swing.JButton autorBarraLateralBtn;
    private javax.swing.JTable autorListagemTbl;
    private javax.swing.JPanel autorPanel;
    private javax.swing.JPanel barraLateralPanel;
    private javax.swing.JButton cadastrarAutorBtn;
    private javax.swing.JButton cadastrarClienteBtn;
    private javax.swing.JPanel cadastroAutorPanel;
    private javax.swing.JPanel cadastroClientePanel;
    private javax.swing.JButton clienteBarraLateralBtn;
    private javax.swing.JTable clienteListagemTbl;
    private javax.swing.JPanel clientePanel;
    private javax.swing.JButton compraBarraLateralBtn;
    private javax.swing.JPanel compraPanel;
    private javax.swing.JFormattedTextField cpfClienteTxt;
    private javax.swing.JFormattedTextField dataNascimentoClienteTxt;
    private javax.swing.JButton deletarAutorBtn;
    private javax.swing.JButton deletarClienteBtn;
    private javax.swing.JLabel fotoClienteLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel listagemAutorPanel;
    private javax.swing.JPanel listagemClientePanel;
    private javax.swing.JButton livroBarraLateralBtn;
    private javax.swing.JPanel livroPanel;
    private javax.swing.JTextField nomeAutorTxt;
    private javax.swing.JTextField nomeClienteTxt;
    private javax.swing.JPanel paiPanel;
    private javax.swing.JButton periodicoBarraLateralBtn;
    private javax.swing.JPanel periodicoPanel;
    private javax.swing.JButton revistaBarraLateralBtn;
    private javax.swing.JPanel revistaPanel;
    private javax.swing.JButton selecionarFotoClienteBtn;
    private javax.swing.JLabel statusAutorLbl;
    private javax.swing.JLabel statusClienteLbl;
    private javax.swing.JFormattedTextField telefoneClienteTxt;
    // End of variables declaration//GEN-END:variables
}
